spring:
  datasource:
      url: jdbc:mysql://145.239.81.249:3306/bd2_hospital_2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: krystian
    password: noniusz
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
